<?php declare(strict_types=1);

namespace Components\Blog;

require_once 'utilities/component.utility.php';

use Exception;
use Models\DB\BlogPost;
use Services\BlogPostScheduleService;
use Utilities\Component;

/** @var string $formId */
/** @var BlogPost $post */

if (empty($formId) || gettype($formId) !== 'string')
    throw new Exception('Form ID string data ($formId) not provided for BlogForm component');
$post ??= null;

$schedule = !$post || $post->publishedOn
    ? false
    : BlogPostScheduleService::getInstance()->getBlogPostSchedule($post->id);

Component::addAttributes(['form-id' => $formId, 'role' => 'form']);
Component::renderCSS();
Component::addJSModule();

?>

<form id="<?= $formId ?>" autocomplete="off">
    <input id="<?= $formId ?>__id"
        type="hidden"
        name="id"
        value="<?= $post?->id ?? 0 ?>">
</form>
<label>
    Title:
    <input id="<?= $formId ?>__title" full-width
        type="text"
        form="<?= $formId ?>"
        name="title"
        placeholder="Title"
        minlength="<?= INPUT_LENGTH['page_title']['min'] ?>"
        maxlength="<?= INPUT_LENGTH['page_title']['max'] ?>"
        pattern="<?= REGEX_HTML['default-text'] ?>"
        value="<?= $post?->title ?>"
        required>
</label>

<blog-form-permalink>
    <?php if ($post?->publishedOn): ?>
        <?php echo $permalink = '/' . PATH_BLOG_PREFIX . $post->permalink ?>
        <input id="<?= $formId ?>__is-published"
            type="hidden"
            form="<?= $formId ?>"
            name="isPublished"
            value="<?= $permalink ?>">
    <?php else: ?>
        <?php 
        $matches = [];
        $permadate = date('Y/m/d');
        $permalinkTitle = '';
        if ($post?->permalink && preg_match(REGEX_PHP['permalink-date-title'], $post->permalink, $matches)) {
            if ($matches[1] > $permadate)
                $permadate = $matches[1];
            
            $permalinkTitle = $matches[2];
        }    
        ?>
        <span>/<?= PATH_BLOG_PREFIX ?>/</span>
        <span id="<?= $formId ?>__permadate"
            data-default="<?= $permadate ?>">
            <?= $permadate ?>
        </span>
        <span>/</span>
        </span>
        <input id="<?= $formId ?>__permalink"
            type="text"
            form="<?= $formId ?>"
            name="permalink"
            placeholder="Permalinks are automatically generated by default"
            pattern="<?= REGEX_HTML['permalink-title'] ?>"
            aria-label="Customizable part of the post's URL (i.e. address)"
            value="<?= $permalinkTitle ?>">
        <button id="<?= $formId ?>__reset-permalink"
            title="Restore default permalink"
            aria-label="Restore default permalink"
            >
            <svg width="1em" height="1em">
                <use xlink:href="#svg-restore-setting" href="#svg-restore-setting"></use>
            </svg>
        </button>
    <?php endif ?>
</blog-form-permalink>

<?php Component::include('text-editor', [
    'attributes' => [ 'id' => "{$formId}__text-editor" ],
    'value' => $post?->contentShort . $post?->contentRest
])  ?>

<input id="<?= $formId ?>__content-short"
    type="hidden"
    form="<?= $formId ?>"
    name="contentShort"
    value="">
<input id="<?= $formId ?>__content-rest"
    type="hidden"
    form="<?= $formId ?>"
    name="contentRest"
    value="">

<label>
    <div>Description:</div>
    <input id="<?= $formId ?>__description" full-width
        type="text"
        form="<?= $formId ?>"
        name="description"
        placeholder="A short description of the contents, for search engine previews, etc."
        minlength="<?= INPUT_LENGTH['page_description']['min'] ?>"
        maxlength="<?= INPUT_LENGTH['page_description']['max'] ?>"
        pattern="<?= REGEX_HTML['default-text'] ?>"
        value="<?= $post?->description ?>"
        required>
</label>
<label>
    Social Link:
    <input id="<?= $formId ?>__mastolink" full-width
        type="url"
        form="<?= $formId ?>"
        name="mastolink"
        placeholder="Social media link connected to this post"
        value="<?= $post?->mastolink ?>">
</label>

<blog-form-options class="form-spaced-row">
    <options-group class="form-row-group">
        <label>
            <input id="<?= $formId ?>__toggle-pinned"
                type="checkbox"
                form="<?= $formId ?>"
                name="isPinned"
                <?= $post?->isPinned ? 'checked' : null ?>
                >
            Pinned
        </label>
        <?php if ($post?->publishedOn): ?>
            <label>
                <input id="<?= $formId ?>__toggle-hidden"
                    type="checkbox"
                    form="<?= $formId ?>"
                    name="isHidden"
                    <?= $post->isHidden ? 'checked' : null ?>
                    >
                Hidden
            </label>
        <?php endif ?>
    </options-group>
    <options-group class="form-row-group">
        <?php if (!$post?->publishedOn): ?>
            <input <?= $schedule ? null : 'disabled hidden'  ?>
                id="<?= $formId ?>__scheduled-date"
                type="date"
                form="<?= $formId ?>"
                name="scheduledDate"
                value="<?= $schedule ? $schedule->publishOn->format('Y-m-d') : null ?>"
                required>
            <input <?= $schedule ? null : 'disabled hidden'  ?>
                id="<?= $formId ?>__scheduled-time"
                type="time"
                form="<?= $formId ?>"
                name="scheduledTime"
                step="60"
                value="<?= $schedule ? $schedule->publishOn->format('H:i') : null ?>"
                required>
            <label>
                <input id="<?= $formId ?>__toggle-schedule"
                    type="checkbox"
                    form="<?= $formId ?>"
                    name="isScheduled"
                    <?= $schedule ? 'checked' : null ?>
                    >
                Schedule
            </label>
        <?php endif ?>
    </options-group>
</blog-form-options>