<?php declare(strict_types=1);

namespace Components\Blog;

require_once 'utilities/component.utility.php';

use Exception;
use Models\DB\BlogPost;
use Utilities\Component;

/** @var string $formId */
/** @var BlogPost $post */

if (empty($formId) || gettype($formId) !== 'string')
    throw new Exception('Form ID string data ($formId) not provided for BlogEditor component');
$post ??= null;

Component::addAttributes(['form-id' => $formId, 'role' => 'form']);
Component::renderCSS();
Component::addJSModule();

?>

<form id="<?= $formId ?>" autocomplete="off">
    <input id="<?= $formId ?>__id"
        type="hidden"
        name="id"
        value="<?= $post?->id ?? 0 ?>">
</form>
<label>
    Title:
    <input id="<?= $formId ?>__title" full-width
        type="text"
        form="<?= $formId ?>"
        name="title"
        placeholder="Title"
        minlength="<?= INPUT_LENGTH['page_title']['min'] ?>"
        maxlength="<?= INPUT_LENGTH['page_title']['max'] ?>"
        pattern="<?= REGEX_HTML['default-text'] ?>"
        value="<?= $post?->title ?>"
        required>
</label>

<blog-editor-permalink>
    <?php if ($post && $post->publishedOn): ?>
        /<?= PATH_BLOG_PREFIX . $post->permalink ?>
        <input id="<?= $formId ?>__is-published"
            type="hidden"
            name="isPublished"
            value="true">
    <?php else: ?>
        <span>/<?= PATH_BLOG_PREFIX ?>/</span>
        <span id="<?= $formId ?>__permadate"
            data-default="<?= date('Y/m/d') ?>">
            <?= date('Y/m/d') ?>
        </span>
        <span>/</span>
        </span>
        <input id="<?= $formId ?>__permalink"
            type="text"
            form="<?= $formId ?>"
            name="permalink"
            placeholder="Permalinks are automatically generated by default"
            pattern="<?= REGEX_HTML['permalink-title'] ?>"
            aria-label="Customizable part of the post's URL (i.e. address)"
            required>
        <button id="<?= $formId ?>__reset-permalink"
            title="Restore default permalink"
            aria-label="Restore default permalink"
            >
            <svg width="1em" height="1em">
                <use xlink:href="#svg-restore-setting" href="#svg-restore-setting"></use>
            </svg>
        </button>
    <?php endif ?>
</blog-editor-permalink>

<?php Component::include('text-editor', [
    'attributes' => [ 'id' => "{$formId}__text-editor" ],
    'value' => $post?->contentShort . $post?->contentRest
])  ?>

<input id="<?= $formId ?>__content-short"
    type="hidden"
    form="<?= $formId ?>"
    name="contentShort"
    value="">
<input id="<?= $formId ?>__content-rest"
    type="hidden"
    form="<?= $formId ?>"
    name="contentRest"
    value="">

<label>
    <div>Description:</div>
    <input id="<?= $formId ?>__description" full-width
        type="text"
        form="<?= $formId ?>"
        name="description"
        placeholder="A short description of the contents, for search engine previews, etc."
        minlength="<?= INPUT_LENGTH['page_description']['min'] ?>"
        maxlength="<?= INPUT_LENGTH['page_description']['max'] ?>"
        pattern="<?= REGEX_HTML['default-text'] ?>"
        value="<?= $post?->description ?>"
        required>
</label>
<label>
    Social Link:
    <input id="<?= $formId ?>__mastolink" full-width
        type="url"
        form="<?= $formId ?>"
        name="mastolink"
        placeholder="Social media link connected to this post"
        value="<?= $post?->mastolink ?>">
</label>