<?php declare(strict_types=1);

namespace Components\Blog;

require_once 'utilities/component.utility.php';

use Enums\UserPermission;
use Services\SessionService;
use Utilities\Component;

$sessionService = SessionService::getInstance(); /** @var SessionService $sessionService */
$sessionService->enforcePermissions([UserPermission::Publishing]);

Component::renderOnce();
Component::renderCSS();
Component::addJSModule();

?>

<button id="blog-head__btn-add"
    type="button"
    class="btn-primary"
    aria-pressed="false"
    aria-controls="blog-head__content"
    title="Loading..."
    data-title-open="Add a new post"
    data-title-close="Hide post form"
    data-path-open="M440-440H200v-80h240v-240h80v240h240v80H520v240h-80v-240Z"
    data-path-close="M240-640v-80h480v80H240Zm56 416-56-56 240-240 240 240-56 56-184-184-184 184Z"
    disabled
    >
    <svg is-loading width="2em" height="2em">
        <use xlink:href="#svg-loading" href="#svg-loading"></use>
    </svg>
    <svg has-loaded width="2em" height="2em" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960">
        <path id="blog-head__btn-add__path" d="M440-440H200v-80h240v-240h80v240h240v80H520v240h-80v-240Z"/>
    </svg>
</button>

<blog-head-content id="blog-head__content" role="form">
    <blog-head-body>
        <form id="blog-head__form" autocomplete="off">
            <input id="blog-head__id"
                type="hidden"
                name="id"
                value="0">
        </form>
        <label>
            Title:
            <input id="blog-head__title" full-width
                type="text"
                form="blog-head__form"
                name="title"
                placeholder="Title"
                minlength="<?= INPUT_LENGTH['page_title']['min'] ?>"
                maxlength="<?= INPUT_LENGTH['page_title']['max'] ?>"
                pattern="<?= REGEX_HTML['default-text'] ?>"
                required>
        </label>
        
        <blog-head-permalink>
            <span>/<?= PATH_BLOG_PREFIX ?>/</span>
            <span id="blog-head__permadate"
                data-default="<?= date('Y/m/d') ?>">
                <?= date('Y/m/d') ?>
            </span>
            <span>/</span>
            </span>
            <input id="blog-head__permalink"
                type="text"
                form="blog-head__form"
                name="permalink"
                placeholder="Permalinks are automatically generated by default"
                pattern="<?= REGEX_HTML['permalink-title'] ?>"
                aria-label="Customizable part of the post's URL (i.e. address)"
                required>
            <button id="blog-head__reset-permalink"
                title="Restore default permalink"
                aria-label="Restore default permalink"
                >
                <svg width="1em" height="1em">
                    <use xlink:href="#svg-restore-setting" href="#svg-restore-setting"></use>
                </svg>
            </button>
        </blog-head-permalink>

        <?php Component::include('text-editor', [
            'attributes' => [ 'id' => 'blog-head__text-editor' ]
        ])  ?>
        
        <input id="blog-head__content-short"
            type="hidden"
            form="blog-head__form"
            name="contentShort"
            value="">
        <input id="blog-head__content-rest"
            type="hidden"
            form="blog-head__form"
            name="contentRest"
            value="">

        <label>
            <div>Description:</div>
            <input id="blog-head__description" full-width
                type="text"
                form="blog-head__form"
                name="description"
                placeholder="A short description of the contents, for search engine previews, etc."
                minlength="<?= INPUT_LENGTH['page_description']['min'] ?>"
                maxlength="<?= INPUT_LENGTH['page_description']['max'] ?>"
                pattern="<?= REGEX_HTML['default-text'] ?>"
                required>
        </label>
        <label>
            Social Link:
            <input id="blog-head__mastolink" full-width
                type="url"
                form="blog-head__form"
                name="mastolink"
                placeholder="Social media link connected to this post">
        </label>
    </blog-head-body>
    <blog-head-footer>
        <blog-head-options>
            <label>
                <input id="blog-head__toggle-pinned"
                    type="checkbox"
                    form="blog-head__form"
                    name="isPinned">
                Pinned
            </label>
            <blog-head-scheduling>
                <input hidden
                    id="blog-head__scheduled-date"
                    type="date"
                    form="blog-head__form"
                    name="scheduledDate">
                <input hidden
                    id="blog-head__scheduled-time"
                    type="time"
                    form="blog-head__form"
                    name="scheduledTime"
                    step="60">
                <label>
                    <input id="blog-head__toggle-schedule"
                        type="checkbox"
                        form="blog-head__form"
                        name="isScheduled">
                    Schedule
                </label>
            </blog-head-scheduling>
        </blog-head-options>
        <blog-head-buttons>
            <button id="blog-head__btn-cancel"
                class="btn-warn btn-hover">
                    Cancel
            </button>
            <blog-head-buttons-save>
                <button id="blog-head__btn-publish"
                    type="submit"
                    form="blog-head__form"
                    class="btn-primary"
                    data-content-publish="Publish"
                    data-content-schedule="Schedule"
                    disabled>
                        Publish
                </button>
                <button id="blog-head__btn-draft"
                    class="btn-secondary"
                    disabled>
                        Save draft
                </button>
        </blog-head-buttons-save>
        </blog-head-buttons>
    </blog-head-footer>
</blog-head-content>